root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
full_bin = ""
include_ext = ["go", "toml"]
exclude_dir = ["tmp", "bin", "node_modules", "vendor", "migrations"]
include_dir = ["cmd", "internal", "pkg"]
exclude_regex = ["_test\\.go$"]
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 0

[log]
time = false
main_only = false

[misc]
clean_on_exit = false