package export

import (
	"bytes"
	"fmt"
	"time"

	"github.com/xuri/excelize/v2"

	"universev2-backend/internal/model"
)

// GenerateRosterExcel creates a real Excel file buffer containing Roster matrix data
func GenerateRosterExcel(key string, month string, dept string, rows []model.RosterExportRow) ([]byte, error) {
	f := excelize.NewFile()
	defer f.Close()

	if month == "" {
		month = time.Now().Format("2006-01")
	}
	if dept == "" {
		dept = "All Department"
	}

	sheetName := "Roster " + month
	index, err := f.NewSheet(sheetName)
	if err != nil {
		return nil, err
	}
	f.SetActiveSheet(index)
	_ = f.DeleteSheet("Sheet1")

	// Set title header
	_ = f.SetCellValue(sheetName, "A1", fmt.Sprintf("LAPORAN ROSTER %s — %s", dept, month))
	_ = f.SetCellValue(sheetName, "A2", "Generated by UniverseV2 System")

	// Set column headers
	headers := []string{"NIK", "Nama Karyawan", "Departemen", "Posisi"}
	for i := 1; i <= 31; i++ {
		headers = append(headers, fmt.Sprintf("%02d", i))
	}

	for colIdx, header := range headers {
		cell, _ := excelize.CoordinatesToCellName(colIdx+1, 4)
		_ = f.SetCellValue(sheetName, cell, header)
	}

	// Real data rows from database
	for rowIdx, emp := range rows {
		r := rowIdx + 5
		_ = f.SetCellValue(sheetName, fmt.Sprintf("A%d", r), emp.NIK)
		_ = f.SetCellValue(sheetName, fmt.Sprintf("B%d", r), emp.Name)
		_ = f.SetCellValue(sheetName, fmt.Sprintf("C%d", r), emp.Dept)
		_ = f.SetCellValue(sheetName, fmt.Sprintf("D%d", r), emp.Pos)

		for day := 1; day <= 31; day++ {
			code := ""
			if emp.Schedules != nil {
				code = emp.Schedules[day]
			}
			cell, _ := excelize.CoordinatesToCellName(day+4, r)
			_ = f.SetCellValue(sheetName, cell, code)
		}
	}

	var buf bytes.Buffer
	if err := f.Write(&buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

